version: '3.11'
services:
web:
build: .
ports:
- "8000:8000"
env_file:
- .env
db:
image: postgres:13
environment:
POSTGRES_DB: your_db
POSTGRES_USER: your_user
POSTGRES_PASSWORD: your_password
ports:
- "5432:5432"