name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        include:
          - python-version: "3.11"
            experimental: false

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest packaging
          
      - name: Run unit tests
        env:
          CI: "true"  # Mark environment as CI
        run: |
          pytest tests/unit/test_environment.py -v --cov --cov-report=xml
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: matrix.experimental == false

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Python version
        run: |
          python -c "import sys; assert sys.version_info >= (3,11), f'Python 3.11+ required, found {sys.version}'"